### ISSUE TITLE
'FindFile' does not work on the mac

### ISSUE THREAD

**Issue by nassersala** [JoshDavid/CEF-Utility#3]
path←FindFile 'find the  file' 
path  ⍝ path is always the file appended to home folder '/users/me/file.csv'

**Comment by JoshDavid** [comment]
Hey, thanks for pointing this out. This function seems to only work in Windows, and actually, it should not work in any OS at all. Looking into it more, the full path is inaccessible via HTML for security reasons. 

It happens to work in Windows by chance. I should remove this function. A better function would be to return a BLOB of the file contents, or some representation of the file. I will close this issue if I implement those. 

Thanks.
-Josh
